apiVersion: v1
kind: Service
metadata:
  name: blackbox
  namespace: monitoring
  labels:
    component: blackbox-exporter
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  ports:
    - nodePort: 31000
      port: 9115
      targetPort: 9115
      protocol: TCP
  selector:
    component: blackbox-exporter 
