apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      component: blackbox-exporter
  template:
    metadata:
      labels:
        component: blackbox-exporter
    spec:
      containers:
        - image: prom/blackbox-exporter:v0.11.0
          args:
            - "--config.file=/etc/config/blackbox.yml"
          name: blackbox-exporter
          ports:
          - containerPort: 9115
            name: metrics
          volumeMounts:
            - name: blackbox-config-volume
              mountPath: /etc/config/
      volumes:
        - name: blackbox-config-volume
          configMap:
            defaultMode: 420
            name: blackbox-exporter-config
