- op: replace
  path: /spec/rules/1/host
  value: template-prometheus.cloudzcp.io

- op: replace
  path: /spec/tls/0/hosts/1
  value: template-prometheus.cloudzcp.io

- op: replace
  path: /metadata/annotations/kubernetes.io~1ingress.class
  value: ingress_class