apiVersion: v1
data:
  node.rules: |
    groups:
    - name: node.rules
      rules:
      - alert: NodeExporterDown
        expr: absent(up{component="node-exporter",job="kubernetes-monitoring-endpoints"} == 1)
        for: 2m
        labels:
          severity: warning
        annotations:
          description: Prometheus could not scrape a node-exporter for more than 10m,or node-exporters have disappeared from discovery.
          summary: node-exporter cannot be scraped
      - alert: NodeCPUUsage
        expr: (100 - (avg by (instance) (irate(node_cpu{job="node-exporter",mode="idle"}[5m])) * 100)) > 90
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "{{$labels.instance}}: High CPU usage detected"
          description: "{{$labels.instance}}: CPU usage is above 90% (current value is: {{ $value }})"
      - alert: NodeLoadAverage5
        expr: ((node_load5 / count without (cpu, mode) (node_cpu{mode="system"})) > 4)
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "{{$labels.instance}}: High Load Average detected"
          description: "{{$labels.instance}}: Load Average is high"
      - alert: NodeMemoryUsage
        expr: (((node_memory_MemTotal-node_memory_MemFree-node_memory_Cached)/(node_memory_MemTotal)*100)) > 90
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "{{$labels.instance}}: High memory usage detected"
          description: "{{$labels.instance}}: Memory usage is above 90% (current value is: {{ $value }})"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-rules
  namespace: monitoring
