apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-block-retain-bronze"
  labels:
    billingType: "hourly"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
