apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    component: grafana
  name: monitoring-grafana-config-provisioning
  namespace: monitoring 
data:
  system.yaml: |
    apiVersion: 1
    providers:
     - name: 'System'
       orgId: 1
       folder: 'System Dashboards'
       type: file
       options:
         path: /var/lib/grafana/dashboards/system
  cluster.yaml: |
    apiVersion: 1
    providers:
     - name: 'Cluster'
       orgId: 1
       folder: 'Cluster Dashboards'
       type: file
       options:
         path: /var/lib/grafana/dashboards/cluster
  container.yaml: |
    apiVersion: 1
    providers:
     - name: 'Container'
       orgId: 1
       folder: 'Container Dashboards'
       type: file
       options:
         path: /var/lib/grafana/dashboards/container
  node.yaml: |
    apiVersion: 1
    providers:
     - name: 'default'
       orgId: 1
       folder: 'Dashboard'
       type: file
       options:
         path: /var/lib/grafana/dashboards/dev
