apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  labels:
    component: kube-state-metrics 
  annotations:
    prometheus.io/scrape: 'true'
  namespace: zcp-system
spec:
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
    protocol: TCP
  selector:
    component: kube-state-metrics 
