apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-state-metrics
  labels:
    component: kube-state-metrics 
spec:
  replicas: 1
  template:
    metadata:
      name: kube-state-metrics
      labels:
        component: kube-state-metrics
    spec:
      serviceAccountName: kube-state-metrics
      containers:
        - name: kube-state-metrics
          image: k8s.gcr.io/kube-state-metrics:v1.3.0
          ports:
          - containerPort: 8080
            name: metric
