- op: replace
  path: /spec/rules/0/host
  value: template-monitoring.cloudzcp.io

- op: replace
  path: /spec/tls/0/hosts/0
  value: template-monitoring.cloudzcp.io

- op: replace
  path: /metadata/annotations/ingress.bluemix.net~1ALB-ID
  value: alb_id